#!/usr/bin/env zsh

# TODO: Use getopt or zparseopts

if [[ $ARGC -le 1 ]]; then
	echo "> Usage: ./test.sh <algo> <file>"
	echo "> Or:    ./test.sh <algo> sample.in <filesize> (filesize in MB)"
	echo "> algo in {des-ecb,idea-ecb,aes-ecb}"
	exit 0
fi

make -s -j5 -C ..

if [[ $1 == "sample.in" && ! -e sample.in ]]; then;
	echo "Creating a $3MB sample.in file..."
	dd bs=1048576 count=$2 if=/dev/urandom of=sample.in
fi

echo "==== $1 tests ===="
echo ">> CUDA encryption"
echo "---------------"
time openssl enc -engine cudamrg -e -$1 -nosalt -v -in sample.in -out $1.out.cudamrg -bufsize 8388608 -K "010101F10101F1F1" 2>/dev/null 
echo -e "\n>> CPU encryption"
echo "--------------"
time openssl enc -e -$1 -nosalt -v -in sample.in -out $1.out.cpu -K "010101F10101F1F1" 2>/dev/null

CHKCPU=`cksum $1.out.cpu|awk {'print $1'}`
CHKCUDA=`cksum $1.out.cudamrg|awk {'print $1'}`

echo ""
if [[ $CHKCPU != $CHKCUDA ]]; then
	echo ">> CAUTION: cksum mismatch!"
	echo ">> CPU: $CHKCPU; CUDA: $CHKCUDA"
else
	echo ">> CKSUM matches"
fi

#rm -rf $1.out.cudamrg $1.out.cpu
